/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddOpenAILegacyProviderRequest,
  ConfigToml,
  GlobalConfig,
  HTTPValidationError,
  OpenAILegacyProviderList,
  UpdateConfigTomlRequest,
  UpdateConfigTomlResponse,
  UpdateGlobalConfigRequest,
  UpdateGlobalConfigResponse,
} from '../models/index';
import {
    AddOpenAILegacyProviderRequestToJSON,
    ConfigTomlFromJSON,
    ConfigTomlToJSON,
    GlobalConfigFromJSON,
    GlobalConfigToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OpenAILegacyProviderListFromJSON,
    UpdateConfigTomlRequestFromJSON,
    UpdateConfigTomlRequestToJSON,
    UpdateConfigTomlResponseFromJSON,
    UpdateConfigTomlResponseToJSON,
    UpdateGlobalConfigRequestFromJSON,
    UpdateGlobalConfigRequestToJSON,
    UpdateGlobalConfigResponseFromJSON,
    UpdateGlobalConfigResponseToJSON,
} from '../models/index';

export interface AddOpenAILegacyProviderRequestConfigPostRequest {
    addOpenAILegacyProviderRequest: AddOpenAILegacyProviderRequest;
}

export interface DeleteOpenAILegacyProviderRequestConfigDeleteRequest {
    name: string;
}

export interface UpdateConfigTomlApiConfigTomlPutRequest {
    updateConfigTomlRequest: UpdateConfigTomlRequest;
}

export interface UpdateGlobalConfigApiConfigPatchRequest {
    updateGlobalConfigRequest: UpdateGlobalConfigRequest;
}

/**
 * 
 */
export class ConfigApi extends runtime.BaseAPI {

    /**
     * List all OpenAI Legacy providers.
     */
    async listOpenAILegacyProvidersApiConfigProvidersOpenaiLegacyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenAILegacyProviderList>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        let urlPath = `/api/config/providers/openai-legacy`;
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => OpenAILegacyProviderListFromJSON(jsonValue));
    }

    async listOpenAILegacyProvidersApiConfigProvidersOpenaiLegacyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenAILegacyProviderList> {
        const response = await this.listOpenAILegacyProvidersApiConfigProvidersOpenaiLegacyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Add or update an OpenAI Legacy provider.
     */
    async addOpenAILegacyProviderApiConfigProvidersOpenaiLegacyPostRaw(requestParameters: AddOpenAILegacyProviderRequestConfigPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlobalConfig>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/api/config/providers/openai-legacy`;
        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddOpenAILegacyProviderRequestToJSON(requestParameters['addOpenAILegacyProviderRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalConfigFromJSON(jsonValue));
    }

    async addOpenAILegacyProviderApiConfigProvidersOpenaiLegacyPost(requestParameters: AddOpenAILegacyProviderRequestConfigPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlobalConfig> {
        const response = await this.addOpenAILegacyProviderApiConfigProvidersOpenaiLegacyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an OpenAI Legacy provider.
     */
    async deleteOpenAILegacyProviderApiConfigProvidersOpenaiLegacyNameDeleteRaw(requestParameters: DeleteOpenAILegacyProviderRequestConfigDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlobalConfig>> {
        const queryParameters: any = {};
        const headerParameters: runtime.HTTPHeaders = {};
        let urlPath = `/api/config/providers/openai-legacy/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));
        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalConfigFromJSON(jsonValue));
    }

    async deleteOpenAILegacyProviderApiConfigProvidersOpenaiLegacyNameDelete(requestParameters: DeleteOpenAILegacyProviderRequestConfigDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlobalConfig> {
        const response = await this.deleteOpenAILegacyProviderApiConfigProvidersOpenaiLegacyNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get kimi-cli config.toml.
     * Get kimi-cli config.toml
     */
    async getConfigTomlApiConfigTomlGetRaw(
initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigToml>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/config/toml`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigTomlFromJSON(jsonValue));
    }

    /**
     * Get kimi-cli config.toml.
     * Get kimi-cli config.toml
     */
    async getConfigTomlApiConfigTomlGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigToml> {
        const response = await this.getConfigTomlApiConfigTomlGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get global (kimi-cli) config snapshot.
     * Get global (kimi-cli) config snapshot
     */
    async getGlobalConfigApiConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlobalConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/config/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalConfigFromJSON(jsonValue));
    }

    /**
     * Get global (kimi-cli) config snapshot.
     * Get global (kimi-cli) config snapshot
     */
    async getGlobalConfigApiConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlobalConfig> {
        const response = await this.getGlobalConfigApiConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update kimi-cli config.toml.
     * Update kimi-cli config.toml
     */
    async updateConfigTomlApiConfigTomlPutRaw(requestParameters: UpdateConfigTomlApiConfigTomlPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateConfigTomlResponse>> {
        if (requestParameters['updateConfigTomlRequest'] == null) {
            throw new runtime.RequiredError(
                'updateConfigTomlRequest',
                'Required parameter "updateConfigTomlRequest" was null or undefined when calling updateConfigTomlApiConfigTomlPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/config/toml`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateConfigTomlRequestToJSON(requestParameters['updateConfigTomlRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateConfigTomlResponseFromJSON(jsonValue));
    }

    /**
     * Update kimi-cli config.toml.
     * Update kimi-cli config.toml
     */
    async updateConfigTomlApiConfigTomlPut(requestParameters: UpdateConfigTomlApiConfigTomlPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateConfigTomlResponse> {
        const response = await this.updateConfigTomlApiConfigTomlPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update global (kimi-cli) default model/thinking.
     * Update global (kimi-cli) default model/thinking
     */
    async updateGlobalConfigApiConfigPatchRaw(requestParameters: UpdateGlobalConfigApiConfigPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateGlobalConfigResponse>> {
        if (requestParameters['updateGlobalConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'updateGlobalConfigRequest',
                'Required parameter "updateGlobalConfigRequest" was null or undefined when calling updateGlobalConfigApiConfigPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/config/`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGlobalConfigRequestToJSON(requestParameters['updateGlobalConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateGlobalConfigResponseFromJSON(jsonValue));
    }

    /**
     * Update global (kimi-cli) default model/thinking.
     * Update global (kimi-cli) default model/thinking
     */
    async updateGlobalConfigApiConfigPatch(requestParameters: UpdateGlobalConfigApiConfigPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateGlobalConfigResponse> {
        const response = await this.updateGlobalConfigApiConfigPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
